# Generated by Django 4.1.7 on 2023-04-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
