# Generated by Django 4.1.7 on 2023-04-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApp', '0003_followerscount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
