# Generated by Django 4.1.7 on 2023-04-02 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApp', '0005_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
