# Generated by Django 4.1.7 on 2023-04-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApp', '0006_alter_posts_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='file',
        ),
    ]
