# Generated by Django 4.1.7 on 2023-04-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApp', '0007_remove_posts_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
