# Generated by Django 4.1.7 on 2023-04-02 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApp', '0009_likepost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikePost',
            new_name='Likes',
        ),
    ]
