# Generated by Django 4.1.7 on 2023-04-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApp', '0010_rename_likepost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='postId',
            field=models.CharField(max_length=500),
        ),
    ]
