# Generated by Django 4.1.7 on 2023-04-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApp', '0011_alter_likes_postid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
